- go.mod
- go.sum
- internal/keystore/keystore.go
- internal/keystore/keystore_test.go
This PR uses `github.com/golang-jwt/jwt`
> Fix jwt vulnerability

- contract/contract.go
- contract/contract_test.go
- node/protocols/data_verification/data_verification.go
- node/protocols/data_verification/data_verification_test.go
Solves https://github.com/filefilego/filefilego/issues/30
> Add file transfer progress monitoring

- cmd/filefilego/main.go
- config/config.go
- config/flags.go
- node/node.go
- node/node_test.go
- node/protocols/super_light_node/super_light_node.go
This PR will resolve this issue: https://github.com/filefilego/filefilego/issues/34
> Add super light node package to protocols

- cmd/filefilego/main.go
- config/config.go
- config/flags.go
- contract/contract.go
- contract/contract_test.go
- internal/cli/commands.go
- node/node.go
- node/node_test.go
- node/protocols/data_query/data_query.go
- node/protocols/data_verification/data_verification.go
- node/protocols/data_verification/data_verification_test.go
- node/protocols/messages/messages.go
- node/protocols/super_light_node/super_light_node.go
- rpc/channel.go
- rpc/channel_test.go
- rpc/data_transfer.go
- rpc/data_transfer_test.go
- rpc/rpc.go
- rpc/transaction.go
This PR resolves the following
https://github.com/filefilego/filefilego/issues/26
> Add data transfer rpc protocol

- DEVELOPMENT.md
- README.md
> Fix: typos

- common/file_utils.go
- common/file_utils_test.go
- contract/contract.go
- contract/contract_test.go
- node/protocols/data_verification/data_verification.go
- node/protocols/data_verification/data_verification_test.go
- rpc/data_transfer.go
- test/e2e/e2e_test.go
This PR fixes this issue: https://github.com/filefilego/filefilego/issues/48
> Fix subsequent file decryption bug

- contract/contract.go
- contract/contract_test.go
- rpc/data_transfer.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/52
> Add fix to prevent multiple decryption

- client/address.go
- client/address_test.go
- client/data_transfer.go
- client/data_transfer_test.go
- cmd/filefilego/main.go
- keystore/key.go
- keystore/keystore.go
- keystore/keystore_test.go
- rpc/address.go
- rpc/address_test.go
- rpc/data_transfer.go
- rpc/data_transfer_test.go
- test/e2e/e2e_test.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/55
> Add rpc method and SDK method

- storage/storage.go
This PR fixes this issue: https://github.com/filefilego/filefilego/issues/59
> Fix the filename html escaping

- README.md
- client/data_transfer.go
- client/data_transfer_test.go
- contract/contract.go
- contract/contract_test.go
- node/protocols/data_verification/data_verification.go
- rpc/data_transfer.go
- rpc/data_transfer_test.go
- test/e2e/e2e_test.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/58
> Add multithreaded file download

- README.md
- blockchain/blockchain.go
- blockchain/blockchain_test.go
- cmd/filefilego/main.go
- config/config.go
- config/flags.go
- node/node_test.go
- node/protocols/block_downloader/block_downloader_test.go
- node/protocols/data_verification/data_verification_test.go
- rpc/address_test.go
- rpc/block_test.go
- rpc/filefilego_test.go
- test/e2e/e2e_test.go
- validator/validator_test.go
This PR fixes the following issue: https://github.com/filefilego/filefilego/issues/68
> Fix default block verification on node startup

- internal/cli/commands.go
This PR solves https://github.com/filefilego/filefilego/issues/71
> Add list address command

- internal/cli/client_commands.go
Change cli command descriptions
> Fix descriptions

- client/address.go
- client/address_test.go
- common/hexutil/hexutil.go
- common/hexutil/hexutil_test.go
- internal/cli/client_commands.go
- internal/cli/commands.go
- keystore/keystore.go
- keystore/keystore_test.go
- rpc/address.go
- rpc/address_test.go
- test/e2e/e2e_test.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/75
> Fix unlock address code to unlock any key

- rpc/channel.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/83
> Add json type

- client/data_transfer.go
- client/data_transfer_test.go
- internal/cli/client_commands.go
- rpc/data_transfer.go
- test/e2e/e2e_test.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/78
> Remove file size from download request

- blockchain/blockchain.go
- blockchain/blockchain_test.go
- client/channel.go
- client/channel_test.go
- rpc/channel.go
- test/e2e/e2e_test.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/88
> Add channel creation to sdk and rpc

- cmd/filefilego/main.go
- contract/contract.go
- test/e2e/e2e_test.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/87
> Add purge function

- client/data_transfer.go
- client/data_transfer_test.go
- contract/contract.go
- contract/contract_test.go
- internal/cli/client_commands.go
- node/protocols/data_verification/data_verification.go
- rpc/data_transfer.go
- test/e2e/e2e_test.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/84
> Add redownload functionality and cancel previous ongoing downloads

- rpc/transaction.go
- rpc/transaction_test.go
Validate raw transactions before broadcast
> Add validation of raw transaction

- node/node.go
This PR fixes the following issue: https://github.com/filefilego/filefilego/issues/105
> Fix empty block response bug

- keystore/keystore.go
- storage/storage.go
- test/e2e/e2e_test.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/111
> Fix file paths

- cmd/filefilego/main.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/115
> Add CORS headers

- blockchain/blockchain.go
- blockchain/blockchain_test.go
- client/transaction.go
- client/transaction_test.go
- rpc/transaction.go
- rpc/transaction_test.go
This PR fixes the following issue: https://github.com/filefilego/filefilego/issues/114
> Add offset and limit to get transaction by address

- cmd/filefilego/main.go
- config/config.go
- config/config_test.go
- config/flags.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/117
> Add disallow methods

- client/address.go
- client/address_test.go
- keystore/keystore.go
- rpc/address.go
- rpc/address_test.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/127
> Add rpc and SDK authorization

- client/data_transfer.go
- client/data_transfer_test.go
- rpc/data_transfer.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/131
> Rebroadcast data query

- node/node.go
- rpc/filefilego.go
- rpc/filefilego_test.go
This PR fixes the following issue: https://github.com/filefilego/filefilego/issues/130
> Add highest block discovered

- blockchain/blockchain.go
- blockchain/blockchain_test.go
- docker-compose.yml
- rpc/filefilego.go
- rpc/filefilego_test.go
Add channel operation fees as a part of the json rpc stats method which will be used by UI to get the fees about channel creation
> Add channel operation fees to rpc stats

- blockchain/blockchain.go
- blockchain/blockchain_test.go
- client/channel.go
- client/channel_test.go
- rpc/channel.go
- rpc/filefilego.go
- test/e2e/e2e_test.go
Add channel fees to HostInfo RPC + channel sorting/indexing https://github.com/filefilego/filefilego/issues/146
> Add channel fees to HostInfo rpc

- Makefile
- blockchain/blockchain.go
- client/data_transfer_test.go
- common/file_utils.go
- contract/contract.go
- contract/contract_test.go
- internal/cli/client_commands.go
- node/node.go
- node/protocols/block_downloader/block_downloader.go
- node/protocols/data_verification/data_verification.go
- node/protocols/data_verification/data_verification_test.go
- node/protocols/storage/storage.go
- rpc/data_transfer.go
- rpc/filefilego.go
- storage/storage.go
- test/e2e/e2e_test.go
- validator/uncommited_balance.go
- validator/validator.go
Fixes this https://github.com/filefilego/filefilego/issues/147
> Add spell check linter

- rpc/channel.go
This PR fixes the following issue: https://github.com/filefilego/filefilego/issues/150
> Add child nodes to GetNodeItem RPC

- blockchain/blockchain.go
- blockchain/blockchain_test.go
- rpc/channel.go
Fixes this: https://github.com/filefilego/filefilego/issues/152
> Add total channel node item child counter

- blockchain/blockchain.go
- blockchain/blockchain_test.go
- rpc/channel.go
This PR closes the following issue: https://github.com/filefilego/filefilego/issues/160
> Add ordering to channel node items

- rpc/storage.go
Fixes: https://github.com/filefilego/filefilego/issues/163
> Add host to struct

- cmd/filefilego/main.go
- node/node.go
- node/protocols/storage/storage.go
- rpc/storage.go
This PR fixes the following issues:
https://github.com/filefilego/filefilego/issues/167
https://github.com/filefilego/filefilego/issues/165
> Improvements to peer finding and add config debug endpoints

- cmd/filefilego/main.go
- rpc/storage.go
- rpc/storage_test.go
- storage/storage.go
- storage/storage_test.go
- test/e2e/e2e_test.go
Fixes this issue: https://github.com/filefilego/filefilego/issues/172
> Add storage list items

- rpc/storage.go
- storage/storage.go
- storage/storage_test.go
This PR fixes the following issue: https://github.com/filefilego/filefilego/issues/174
> Add count to total uploaded files

- cmd/filefilego/main.go
- node/protocols/data_verification/data_verification.go
- node/protocols/data_verification/data_verification_test.go
- rpc/data_transfer_test.go
- test/e2e/e2e_test.go
This PR fixes the following issue: https://github.com/filefilego/filefilego/issues/185
> Add zero fees data download with seeking support

- cmd/filefilego/main.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/177
> Tune goleveldb and add corrupted recovery

- rpc/storage.go
Fixes https://github.com/filefilego/filefilego/issues/192
> Add the fileds to storage rpc

- cmd/filefilego/main.go
- node/node.go
- node/node_test.go
- node/protocols/data_verification/data_verification.go
- node/protocols/data_verification/data_verification_test.go
- node/protocols/storage/storage.go
- node/protocols/storage/storage_test.go
- rpc/filefilego_test.go
- rpc/storage.go
- storage/storage.go
- storage/storage_test.go
- test/e2e/e2e_test.go
This PR solves the following issue: https://github.com/filefilego/filefilego/issues/194
> Refactor storage engine

- cmd/filefilego/main.go
- rpc/storage.go
- test/e2e/e2e_test.go
This PR adds a queue to file uploader functionality in: https://github.com/filefilego/filefilego/issues/182
> Add upload queue

- docker-compose.yml
- rpc/storage.go
This PR fixes the following issue:
https://github.com/filefilego/filefilego/issues/202
> Add multiple files in RPC request

- node/protocols/storage/storage.go
- rpc/storage.go
Closes https://github.com/filefilego/filefilego/issues/204
> Add multi file progress indicator

- rpc/storage.go
Add filepath to response when uploading a file so UI can attach it to internal progress bar
> Add filepath to response for UI

- cmd/filefilego/main.go
Initialize storge package for superlight clients, to support sving uploaded meadata to remote nodes
> Refactor main to start storage under superlight node

- rpc/data_transfer.go
Fixes this: https://github.com/filefilego/filefilego/issues/211
> Fix zero fee contracts

- rpc/data_transfer.go
This PR fixes the following: https://github.com/filefilego/filefilego/issues/216
> Add rpc methods to data transfer

- rpc/storage.go
- storage/storage.go
Fixes the following issues:
https://github.com/filefilego/filefilego/issues/219
https://github.com/filefilego/filefilego/issues/220
> Fix storage bug

- docker-compose.yml
- rpc/data_transfer.go
This PR fixes: https://github.com/filefilego/filefilego/issues/223
> Fix progress bug

- common/file_utils.go
- common/file_utils_test.go
- node/node.go
- node/protocols/data_verification/data_verification.go
- node/protocols/storage/storage.go
- node/protocols/storage/storage_test.go
- rpc/data_transfer.go
- rpc/storage.go
- storage/storage.go
This PR fixes some bugs and adds context cancellation + rpc upload cancellation
> Fix bugs and add context cancellation

- docker-compose.yml
- rpc/data_transfer.go
Fix a small issue related to pausing file downloads
> Update docker compose

- contract/contract.go
- rpc/data_transfer.go
With this PR the UI client can determine the stats of the download
> Add paused file download indicator

- node/protocols/data_verification/data_verification.go
- rpc/data_transfer.go
Closes opened file handlers
See: https://github.com/filefilego/filefilego-ui/issues/14
> Fix closing file handlers

- rpc/transaction.go
- rpc/transaction_test.go
This PR fixes the following issue: https://github.com/filefilego/filefilego/issues/258
> Add CreateTransaction endpoint

- cmd/filefilego/main.go
- database/database.go
- database/database_test.go
- node/protocols/storage/storage_test.go
- rpc/storage.go
- rpc/storage_test.go
- storage/storage.go
- test/e2e/e2e_test.go
This PR solves the following issue:
https://github.com/filefilego/filefilego/issues/260
> Add file deletion from local storage node + db

- cmd/filefilego/main.go
- node/protocols/data_verification/data_verification.go
- node/protocols/data_verification/data_verification_test.go
- node/protocols/storage/storage_test.go
- rpc/data_transfer_test.go
- test/e2e/e2e_test.go
This PR solves:
https://github.com/filefilego/filefilego/issues/262
> View images in channels

- cmd/filefilego/main.go
- node/protocols/data_verification/data_verification.go
- node/protocols/data_verification/data_verification_test.go
- rpc/data_transfer.go
- rpc/data_transfer_test.go
- test/e2e/e2e_test.go
This PR fixes https://github.com/filefilego/filefilego/issues/262
> Add media downloader

- blockchain/blockchain.go
- blockchain/blockchain_test.go
- rpc/channel.go
Fixes this feature: https://github.com/filefilego/filefilego-ui/issues/19
> Add pagination

- storage/storage.go
- storage/storage_test.go
Decrement the total uploaded files count when a file is deleted
> Decrement count when an uploaded file is deleted

- cmd/filefilego/main.go
- common/common.go
- common/common_test.go
- node/node.go
- node/protocols/data_verification/data_verification_test.go
- rpc/storage.go
- storage/storage.go
- storage/storage_test.go
Fixes the following issue: https://github.com/filefilego/filefilego/issues/241
> Add timestamp to uploaded files

- cmd/filefilego/main.go
- node/protocols/data_verification/data_verification_test.go
- rpc/storage.go
- storage/storage.go
- storage/storage_test.go
Fixes the following issue: https://github.com/filefilego/filefilego/issues/274
> Move the endpoints to storage RPC

- Makefile
- common/common.go
- common/common_test.go
- node/protocols/data_verification/data_verification.go
- node/protocols/data_verification/data_verification_test.go
- rpc/data_transfer.go
This PR propagates the dynamic fees of files to download contracts
> Add file fees to download contract logic

- rpc/storage.go
Return the indication of allow fees override in storage provider discovery
> Add allow fees overidde to storage discovery

- PROOF_TRANSFER.md
Add proof of data transfer documentation
> Add proof of data transfer

- go.mod
- go.sum
- node/protocols/data_verification/data_verification.go
Add retry when sending the data to verifier, covers #99
> send the data to verifier with exponential retry mechanism

- block/block.proto
- block/reward.go
- blockchain/blockchain.go
- client/client.go
- cmd/filefilego/main.go
- contract/contract.go
- database/database.go
- internal/cli/commands.go
- keystore/key.go
- node/node_test.go
- search/bleve.go
- search/bleve_test.go
- storage/storage.go
- transaction/transaction.go
Add some improvements and comments
> Add improvements
